"""Emit a standalone script that appends mined factors to the source dataset.

The generated file depends on nothing but numpy, pandas and pyarrow, so it runs on the
training host without installing Helix. It carries its own copies of the operators and
the slot-packing logic, and evaluates the stored expressions with :func:`eval` against a
namespace containing only those operators and the feature grids -- the printed DEAP form
is already valid Python under that namespace.

The factor values it produces are identical to the ones scored during the search: same
packing, same operators, same sign convention (higher = more likely to hit the target).
"""

from __future__ import annotations

import json
from pathlib import Path

from ..data.event_table import LABEL_PREFIXES, assert_no_label_columns, is_label_column
from ..logging_setup import get_logger
from .library import FactorLibrary

log = get_logger(__name__)

GP_FACTOR_AUDIT_COLUMNS = (
    "gp_factor_source_date",
    "gp_factor_as_of_time",
    "gp_factor_price_basis",
    "gp_factor_adj_factor_version",
)

_TEMPLATE = '''#!/usr/bin/env python3
"""Auto-generated by helix export -- do not edit by hand.

Appends {n_factors} mined factor columns to a long-format event table and reports
per-date IC / IC_IR for each one.

    python apply_factors.py --input train_dataset_merged.parquet \\
                            --lineage event-lineage.json \\
                            --calendar trading-calendar.parquet \\
                            --output train_dataset_with_factors.parquet \\
                            --output-lineage train_dataset_with_factors.lineage.json

Requires only numpy / pandas / pyarrow. Factors are oriented so that a HIGHER value
means MORE likely to reach the target.
"""

from __future__ import annotations

import argparse
import json
import re
import warnings
from datetime import datetime, time, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

DATE_COLUMN = {date_column!r}
CODE_COLUMN = {code_column!r}
FIELD_NAMES = {field_names}
FACTORS = json.loads({factors_json!r})
IC_TARGETS = {ic_targets}
SEARCH_END = {search_end!r}
LABEL_PREFIXES = tuple(json.loads({label_prefixes_json!r}))

GP_SOURCE_DATE = {gp_source_date!r}
GP_AS_OF_TIME = {gp_as_of_time!r}
GP_PRICE_BASIS = {gp_price_basis!r}
GP_ADJ_FACTOR_VERSION = {gp_adj_factor_version!r}
VERSION_RE = re.compile(r"raw-times-same-day-adj-v1:[0-9a-f]{{64}}")
AS_OF_RE = re.compile(
    r"[0-9]{{4}}-[0-9]{{2}}-[0-9]{{2}}T[0-9]{{2}}:[0-9]{{2}}:[0-9]{{2}}"
    r"(?:\\.[0-9]+)?[+-][0-9]{{2}}:[0-9]{{2}}"
)

EPS = 1e-9


# -------------------------------------------------------------- input governance --
def lineage_error(message):
    raise SystemExit("event lineage validation failed: " + message)


def is_outcome_column(name):
    lowered = name.lower()
    return any(lowered.startswith(prefix) for prefix in LABEL_PREFIXES)


def validate_feature_names(names):
    leaked = [name for name in names if is_outcome_column(name)]
    if leaked:
        lineage_error(
            "outcome columns reached the feature set: %s. "
            "Any label-derived input makes the reported IC meaningless." % leaked
        )


def validate_factor_names(names, retained_columns=()):
    invalid = [name for name in names if type(name) is not str or not name.isidentifier()]
    if invalid:
        lineage_error("invalid factor output name: %s" % invalid)
    duplicates = sorted({{name for name in names if names.count(name) > 1}})
    if duplicates:
        lineage_error("duplicate factor output name: %s" % duplicates)
    reserved = {{
        DATE_COLUMN,
        CODE_COLUMN,
        *FIELD_NAMES,
        *IC_TARGETS,
        GP_SOURCE_DATE,
        GP_AS_OF_TIME,
        GP_PRICE_BASIS,
        GP_ADJ_FACTOR_VERSION,
        *retained_columns,
    }}
    collisions = sorted(
        name for name in names if name in reserved or is_outcome_column(name)
    )
    if collisions:
        lineage_error("factor output name collides with retained/reserved columns: %s" % collisions)


def plan_artifact_paths(args, parser):
    if args.output_lineage and not args.output:
        parser.error("--output-lineage requires --output")
    output_lineage = (
        args.output_lineage or (args.output + ".lineage.json")
        if args.output
        else ""
    )
    protected = [
        ("--input", args.input),
        ("--lineage", args.lineage),
        ("--calendar", args.calendar),
    ]
    artifacts = [("--report", args.report)]
    if args.output:
        artifacts.extend(
            [("--output", args.output), ("--output-lineage", output_lineage)]
        )
    resolved_protected = [
        (flag, Path(path).expanduser().resolve()) for flag, path in protected
    ]
    resolved_artifacts = [
        (flag, Path(path).expanduser().resolve()) for flag, path in artifacts
    ]
    for index, (left_flag, left_path) in enumerate(resolved_artifacts):
        for right_flag, right_path in [
            *resolved_protected,
            *resolved_artifacts[index + 1 :],
        ]:
            if left_path == right_path:
                lineage_error(
                    "artifact path collision: %s and %s resolve to %s"
                    % (left_flag, right_flag, left_path)
                )
    return output_lineage


def parse_date(value, field, row):
    if type(value) is not str:
        lineage_error("field %r source date must be a literal string at row %d" % (field, row))
    try:
        if re.fullmatch(r"[0-9]{{8}}", value):
            return datetime.strptime(value, "%Y%m%d").date()
        if re.fullmatch(r"[0-9]{{4}}-[0-9]{{2}}-[0-9]{{2}}", value):
            return datetime.strptime(value, "%Y-%m-%d").date()
    except ValueError:
        pass
    lineage_error("field %r has invalid source date %r at row %d" % (field, value, row))


def parse_as_of(value, source, field, row):
    if type(value) is not str or not AS_OF_RE.fullmatch(value):
        lineage_error("field %r has invalid as_of_time %r at row %d" % (field, value, row))
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError:
        lineage_error("field %r has invalid as_of_time %r at row %d" % (field, value, row))
    if parsed.utcoffset() != timedelta(hours=8):
        lineage_error("field %r as_of_time must use +08:00 at row %d" % (field, row))
    if parsed.date() != source:
        lineage_error("field %r as_of_time is not local to source_date at row %d" % (field, row))
    if parsed.timetz().replace(tzinfo=None) > time(15):
        lineage_error("field %r as_of_time is after market close at row %d" % (field, row))
    return parsed


def load_manifest(path):
    try:
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError, TypeError) as exc:
        lineage_error("invalid manifest %s: %s" % (path, exc))
    if type(payload) is not dict or set(payload) != {{"schema_version", "fields"}}:
        lineage_error("manifest root must contain exactly schema_version and fields")
    if type(payload["schema_version"]) is not int or payload["schema_version"] != 1:
        lineage_error("manifest schema_version must be integer 1")
    if type(payload["fields"]) is not dict:
        lineage_error("manifest fields must be an object")
    required = {{"source_date", "as_of_time", "price_basis", "adj_factor_version", "horizon"}}
    for field, entry in payload["fields"].items():
        if type(field) is not str or not field or type(entry) is not dict or set(entry) != required:
            lineage_error("manifest field %r has an invalid entry" % field)
        for key in ("source_date", "as_of_time", "price_basis", "adj_factor_version"):
            if type(entry[key]) is not str or not entry[key]:
                lineage_error("manifest field %r %s must be a non-empty string" % (field, key))
        if type(entry["horizon"]) is not int or entry["horizon"] < 0:
            lineage_error("manifest field %r horizon must be an integer >= 0" % field)
    return payload


def load_calendar(path):
    try:
        calendar_path = Path(path)
        if calendar_path.suffix.lower() in (".parquet", ".pq"):
            frame = pd.read_parquet(calendar_path)
        elif calendar_path.suffix.lower() == ".csv":
            frame = pd.read_csv(calendar_path, dtype=str)
        else:
            lineage_error("calendar must be parquet or CSV")
    except (OSError, UnicodeError, TypeError, ValueError) as exc:
        lineage_error("invalid calendar %s: %s" % (path, exc))
    date_column = "cal_date" if "cal_date" in frame else "trade_date"
    if date_column not in frame:
        lineage_error("calendar needs cal_date or trade_date")
    if "is_open" in frame:
        keep = []
        for row, value in enumerate(frame["is_open"].tolist()):
            valid = (
                type(value) is str and value in {{"0", "1"}}
            ) or (
                type(value) in (int, float)
                and np.isfinite(value)
                and float(value).is_integer()
                and int(value) in {{0, 1}}
            )
            if not valid:
                lineage_error("calendar has invalid is_open %r at row %d" % (value, row))
            keep.append(int(value) == 1)
        frame = frame.loc[keep]
    raw = frame[date_column].tolist()
    parsed = [parse_date(value, "calendar", row) for row, value in enumerate(raw)]
    if not parsed:
        lineage_error("calendar is empty")
    if any(right <= left for left, right in zip(parsed, parsed[1:])):
        lineage_error("calendar sessions must be strictly increasing and unique")
    return parsed


def validate_governed_input(df, payload, calendar, feature_fields, outcome_fields):
    fields = payload["fields"]
    calendar_positions = {{session: position for position, session in enumerate(calendar)}}
    decisions = [
        parse_date(value, DATE_COLUMN, row)
        for row, value in enumerate(df[DATE_COLUMN].tolist())
    ]
    common_version = None
    feature_asofs = {{}}
    for role, names in (("feature", feature_fields), ("outcome", outcome_fields)):
        for field in names:
            entry = fields.get(field)
            if entry is None:
                lineage_error("field %r has no event lineage manifest entry" % field)
            if role == "feature" and entry["horizon"] != 0:
                lineage_error("feature field %r must declare horizon=0" % field)
            required = [
                field,
                entry["source_date"],
                entry["as_of_time"],
                entry["price_basis"],
                entry["adj_factor_version"],
            ]
            missing = [column for column in required if column not in df]
            if missing:
                lineage_error("field %r is missing governed columns %s" % (field, missing))
            parsed_asofs = []
            rows = zip(
                df[entry["source_date"]].tolist(),
                df[entry["as_of_time"]].tolist(),
                df[entry["price_basis"]].tolist(),
                df[entry["adj_factor_version"]].tolist(),
            )
            for row, (source_value, as_of_value, basis, version) in enumerate(rows):
                if type(basis) is not str or basis != "hfq":
                    lineage_error(
                        "field %r price_basis must be literal hfq at row %d" % (field, row)
                    )
                if type(version) is not str or not VERSION_RE.fullmatch(version):
                    lineage_error(
                        "field %r has unsupported adj_factor_version at row %d" % (field, row)
                    )
                if common_version is None:
                    common_version = version
                elif version != common_version:
                    lineage_error(
                        "field %r has inconsistent adjustment version at row %d" % (field, row)
                    )
                source = parse_date(source_value, field, row)
                parsed_asofs.append(parse_as_of(as_of_value, source, field, row))
                decision_position = calendar_positions.get(decisions[row])
                if decision_position is None:
                    lineage_error(
                        "field %r decision date is absent from calendar at row %d" % (field, row)
                    )
                expected_position = decision_position + entry["horizon"]
                expected = calendar[expected_position] if expected_position < len(calendar) else None
                if source != expected:
                    lineage_error(
                        "field %r horizon=%d source mismatch at row %d: got %s expected %s"
                        % (field, entry["horizon"], row, source, expected)
                    )
            if role == "feature":
                feature_asofs[field] = parsed_asofs
    return common_version, feature_asofs


# --------------------------------------------------------------------- operators --
def _nan_mean_std(x):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        return (np.nanmean(x, axis=1, keepdims=True), np.nanstd(x, axis=1, keepdims=True))


def add(x, y): return x + y
def sub(x, y): return x - y
def mul(x, y): return x * y


def div(x, y):
    with np.errstate(divide="ignore", invalid="ignore"):
        return np.where(np.abs(y) < EPS, np.nan, x / np.where(np.abs(y) < EPS, 1.0, y))


def neg(x): return -x
def abs_(x): return np.abs(x)
def sign(x): return np.sign(x)
def log_abs(x): return np.sign(x) * np.log1p(np.abs(x))
def sqrt_abs(x): return np.sign(x) * np.sqrt(np.abs(x))


def cs_rank(x):
    filled = np.where(np.isnan(x), np.inf, x)
    order = np.argsort(filled, axis=1, kind="stable")
    positions = np.broadcast_to(np.arange(1, x.shape[1] + 1, dtype=np.float64), x.shape)
    ranks = np.empty(x.shape, dtype=np.float64)
    np.put_along_axis(ranks, order, positions, axis=1)
    valid = ~np.isnan(x)
    counts = np.maximum(valid.sum(axis=1, keepdims=True), 1)
    return np.where(valid, ranks / counts, np.nan)


def cs_zscore(x):
    mean, std = _nan_mean_std(x)
    return np.where(std < EPS, np.nan, (x - mean) / np.where(std < EPS, 1.0, std))


def cs_demean(x):
    mean, _ = _nan_mean_std(x)
    return x - mean


OPS = {{
    "add": add, "sub": sub, "mul": mul, "div": div,
    "neg": neg, "abs": abs_, "sign": sign, "log": log_abs, "sqrt": sqrt_abs,
    "cs_rank": cs_rank, "cs_zscore": cs_zscore, "cs_demean": cs_demean,
}}


# ------------------------------------------------------------------ slot packing --
def pack(df, columns):
    """Long frame -> (T, N_max) slot grids. Slot j is a DIFFERENT stock on each date.

    Grids are built at float32 and only then widened to float64, mirroring Helix's own
    packing exactly. This is not cosmetic: cs_rank sorts, and float32 rounding can make
    two float64-distinct values tie, which would reorder ranks relative to the search.
    """
    dates, date_pos = np.unique(df[DATE_COLUMN].to_numpy(), return_inverse=True)
    counts = np.bincount(date_pos, minlength=len(dates))
    n_max = int(counts.max())
    starts = np.concatenate([[0], np.cumsum(counts)[:-1]])
    slot = np.arange(len(df)) - np.repeat(starts, counts)

    occupied = np.zeros((len(dates), n_max), dtype=bool)
    occupied[date_pos, slot] = True

    grids = {{}}
    for column in columns:
        grid = np.full((len(dates), n_max), np.nan, dtype=np.float32)
        grid[date_pos, slot] = pd.to_numeric(df[column], errors="coerce").to_numpy()
        grids[column] = grid.astype(np.float64)
    return dates, date_pos, slot, occupied, grids


# ------------------------------------------------------------------------- metrics --
def daily_ic(factor, target, mask, min_samples=30):
    valid = mask & np.isfinite(factor) & np.isfinite(target)
    x = cs_rank(np.where(valid, factor, np.nan))
    y = cs_rank(np.where(valid, target, np.nan))
    w = valid.astype(np.float64)
    xs, ys = np.nan_to_num(x) * w, np.nan_to_num(y) * w
    n = w.sum(axis=1)
    sx, sy = xs.sum(axis=1), ys.sum(axis=1)
    cov = n * (xs * ys).sum(axis=1) - sx * sy
    vx = n * (xs * xs).sum(axis=1) - sx * sx
    vy = n * (ys * ys).sum(axis=1) - sy * sy
    denom = np.sqrt(np.maximum(vx, 0) * np.maximum(vy, 0))
    with np.errstate(invalid="ignore", divide="ignore"):
        ic = np.where(denom > 0, cov / np.where(denom > 0, denom, 1.0), np.nan)
    return np.where(n >= min_samples, ic, np.nan)


def summarize(ic):
    f = ic[np.isfinite(ic)]
    if f.size == 0:
        return {{}}
    mean = float(f.mean())
    std = float(f.std(ddof=1)) if f.size > 1 else float("nan")
    icir = mean / std if std and std > 0 else float("nan")
    return {{
        "ic_mean": round(mean, 6),
        "ic_std": round(std, 6),
        "icir": round(icir, 4),
        "icir_ann": round(icir * np.sqrt(252), 3),
        "t_stat": round(icir * np.sqrt(f.size), 3),
        "positive_rate": round(float((f > 0).mean()), 4),
        "n_days": int(f.size),
    }}


# ---------------------------------------------------------------------------- main --
def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input", required=True)
    ap.add_argument("--lineage", required=True, help="Schema-v1 lineage manifest for --input.")
    ap.add_argument(
        "--calendar", required=True, help="Independent authoritative trading calendar."
    )
    ap.add_argument("--output", default="")
    ap.add_argument(
        "--output-lineage",
        default="",
        help="Lineage sidecar for --output (default: <output>.lineage.json).",
    )
    ap.add_argument("--report", default="factor_ic_report.json")
    ap.add_argument("--min-samples", type=int, default=30)
    ap.add_argument(
        "--ic-since", default=SEARCH_END,
        help="Only score dates strictly after this one. Defaults to the last date the "
             "factors were mined on, so the reported IC is genuinely out-of-sample. "
             "Pass an empty string to score the full history instead.",
    )
    args = ap.parse_args()

    validate_feature_names(FIELD_NAMES)
    factor_names = [spec["name"] for spec in FACTORS]
    validate_factor_names(factor_names)
    output_lineage = plan_artifact_paths(args, ap)
    if Path(args.input).resolve() == Path(args.calendar).resolve():
        lineage_error("event trading calendar must be supplied independently")

    df = pd.read_parquet(args.input)
    validate_factor_names(factor_names, df.columns)
    missing = [c for c in FIELD_NAMES if c not in df.columns]
    if missing:
        raise SystemExit("input is missing required feature columns: %s" % missing[:10])
    if DATE_COLUMN not in df or CODE_COLUMN not in df:
        lineage_error("input needs %r and %r columns" % (DATE_COLUMN, CODE_COLUMN))

    payload = load_manifest(args.lineage)
    calendar = load_calendar(args.calendar)
    targets = [t for t in IC_TARGETS if t in df.columns]
    common_version, feature_asofs = validate_governed_input(
        df, payload, calendar, list(FIELD_NAMES), targets
    )
    audit_columns = {{GP_SOURCE_DATE, GP_AS_OF_TIME, GP_PRICE_BASIS, GP_ADJ_FACTOR_VERSION}}
    collisions = sorted(audit_columns & set(df.columns))
    if collisions:
        lineage_error("output factor audit columns already exist: %s" % collisions)
    df[GP_SOURCE_DATE] = df[DATE_COLUMN].astype(str)
    df[GP_AS_OF_TIME] = [
        max(values).isoformat()
        for values in zip(*(feature_asofs[name] for name in FIELD_NAMES))
    ]
    df[GP_PRICE_BASIS] = "hfq"
    df[GP_ADJ_FACTOR_VERSION] = common_version

    df[DATE_COLUMN] = df[DATE_COLUMN].astype(str)
    df[CODE_COLUMN] = df[CODE_COLUMN].astype(str)
    order = np.lexsort((df[CODE_COLUMN].to_numpy(), df[DATE_COLUMN].to_numpy()))
    df = df.iloc[order].reset_index(drop=True)

    dates, date_pos, slot, occupied, grids = pack(df, list(FIELD_NAMES) + targets)
    print("packed %d dates x %d slots (%d rows)" % (len(dates), occupied.shape[1], len(df)))

    # Factor columns are written for every row; IC is only measured after the search
    # window, otherwise the number reported here is partly in-sample.
    scored = occupied & (dates > args.ic_since)[:, None] if args.ic_since else occupied
    print("scoring IC on %d of %d dates (--ic-since %r)" % (
        int((scored.any(axis=1)).sum()), len(dates), args.ic_since))

    namespace = {{**OPS, **{{name: grids[name] for name in FIELD_NAMES}}}}
    report = {{"_meta": {{"ic_since": args.ic_since, "n_dates_scored": int(scored.any(axis=1).sum())}}}}
    for spec in FACTORS:
        with np.errstate(all="ignore"):
            values = eval(spec["expression"], {{"__builtins__": {{}}}}, namespace)  # noqa: S307
        values = np.where(np.isfinite(values), values, np.nan) * spec["sign"]
        df[spec["name"]] = values[date_pos, slot]

        entry = {{"expression": spec["expression"], "sign": spec["sign"]}}
        for target in targets:
            entry[target] = summarize(
                daily_ic(values, grids[target], scored, args.min_samples)
            )
        report[spec["name"]] = entry
        head = entry.get(targets[0], {{}}) if targets else {{}}
        print("  %-12s IC %+.5f  ICIR %+.3f  ann %+.2f  pos %.1f%%  %s" % (
            spec["name"], head.get("ic_mean", float("nan")), head.get("icir", float("nan")),
            head.get("icir_ann", float("nan")), 100 * head.get("positive_rate", float("nan")),
            spec["expression"][:60],
        ))

    with open(args.report, "w") as fh:
        json.dump(report, fh, indent=2, ensure_ascii=False)
    print("wrote %s" % args.report)

    if args.output:
        df.to_parquet(args.output, index=False, compression="zstd")
        factor_entry = {{
            "source_date": GP_SOURCE_DATE,
            "as_of_time": GP_AS_OF_TIME,
            "price_basis": GP_PRICE_BASIS,
            "adj_factor_version": GP_ADJ_FACTOR_VERSION,
            "horizon": 0,
        }}
        output_payload = {{
            "schema_version": 1,
            "fields": {{
                **payload["fields"],
                **{{spec["name"]: dict(factor_entry) for spec in FACTORS}},
            }},
        }}
        Path(output_lineage).write_text(
            json.dumps(output_payload, indent=2, ensure_ascii=False) + "\\n",
            encoding="utf-8",
        )
        print("wrote %s (%d columns, +%d factors)" % (
            args.output, df.shape[1], len(FACTORS)))
        print("wrote %s" % output_lineage)


if __name__ == "__main__":
    main()
'''


def render_apply_script(
    library: FactorLibrary,
    ic_targets: list[str],
    date_column: str = "trade_date",
    code_column: str = "stock_code",
    search_end: str = "",
) -> str:
    """Build the standalone script source for ``library``."""
    if library.kind != "event":
        raise ValueError(f"apply-script export is for event libraries, got {library.kind!r}")

    try:
        assert_no_label_columns(library.field_names)
    except AssertionError as exc:
        raise ValueError(str(exc)) from exc
    invalid = [n for n in library.field_names if not n.isidentifier()]
    if invalid:
        raise ValueError(
            f"these column names are not valid Python identifiers and cannot appear in an "
            f"evaluated expression: {invalid}"
        )

    factor_names = [factor.name for factor in library.factors]
    invalid_factor_names = [
        name
        for name in factor_names
        if type(name) is not str or not name.isidentifier()
    ]
    if invalid_factor_names:
        raise ValueError(f"invalid factor output name: {invalid_factor_names}")
    duplicate_factor_names = sorted(
        {name for name in factor_names if factor_names.count(name) > 1}
    )
    if duplicate_factor_names:
        raise ValueError(f"duplicate factor output name: {duplicate_factor_names}")
    reserved_names = {
        date_column,
        code_column,
        *library.field_names,
        *ic_targets,
        *GP_FACTOR_AUDIT_COLUMNS,
    }
    colliding_factor_names = sorted(
        name
        for name in factor_names
        if name in reserved_names or is_label_column(name)
    )
    if colliding_factor_names:
        raise ValueError(
            "factor output name collides with retained/reserved columns: "
            f"{colliding_factor_names}"
        )

    factors = [
        {"name": f.name, "expression": f.expression, "sign": f.sign} for f in library.factors
    ]
    return _TEMPLATE.format(
        n_factors=len(factors),
        date_column=date_column,
        code_column=code_column,
        search_end=search_end,
        field_names=json.dumps(library.field_names, indent=4),
        factors_json=json.dumps(factors, ensure_ascii=False),
        ic_targets=json.dumps(ic_targets),
        label_prefixes_json=json.dumps(LABEL_PREFIXES),
        gp_source_date=GP_FACTOR_AUDIT_COLUMNS[0],
        gp_as_of_time=GP_FACTOR_AUDIT_COLUMNS[1],
        gp_price_basis=GP_FACTOR_AUDIT_COLUMNS[2],
        gp_adj_factor_version=GP_FACTOR_AUDIT_COLUMNS[3],
    )


def write_apply_script(
    path: Path, library: FactorLibrary, ic_targets: list[str], search_end: str = ""
) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        render_apply_script(library, ic_targets, search_end=search_end), encoding="utf-8"
    )
    path.chmod(0o755)
    log.info("wrote standalone apply script for %d factors to %s", len(library.factors), path)
    return path
