"""Emit a standalone script that appends mined factors to the source dataset.

The generated file depends on nothing but numpy, pandas and pyarrow, so it runs on the
training host without installing Helix. It carries its own copies of the operators and
the slot-packing logic, and evaluates the stored expressions with :func:`eval` against a
namespace containing only those operators and the feature grids -- the printed DEAP form
is already valid Python under that namespace.

The factor values it produces are identical to the ones scored during the search: same
packing, same operators, same sign convention (higher = more likely to hit the target).
"""

from __future__ import annotations

import json
from pathlib import Path

from ..logging_setup import get_logger
from .library import FactorLibrary

log = get_logger(__name__)

_TEMPLATE = '''#!/usr/bin/env python3
"""Auto-generated by helix export -- do not edit by hand.

Appends {n_factors} mined factor columns to a long-format event table and reports
per-date IC / IC_IR for each one.

    python apply_factors.py --input train_dataset_merged.parquet \\
                            --output train_dataset_with_factors.parquet

Requires only numpy / pandas / pyarrow. Factors are oriented so that a HIGHER value
means MORE likely to reach the target.
"""

from __future__ import annotations

import argparse
import json
import warnings

import numpy as np
import pandas as pd

DATE_COLUMN = {date_column!r}
CODE_COLUMN = {code_column!r}
FIELD_NAMES = {field_names}
FACTORS = json.loads({factors_json!r})
IC_TARGETS = {ic_targets}
SEARCH_END = {search_end!r}

EPS = 1e-9


# --------------------------------------------------------------------- operators --
def _nan_mean_std(x):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        return (np.nanmean(x, axis=1, keepdims=True), np.nanstd(x, axis=1, keepdims=True))


def add(x, y): return x + y
def sub(x, y): return x - y
def mul(x, y): return x * y


def div(x, y):
    with np.errstate(divide="ignore", invalid="ignore"):
        return np.where(np.abs(y) < EPS, np.nan, x / np.where(np.abs(y) < EPS, 1.0, y))


def neg(x): return -x
def abs_(x): return np.abs(x)
def sign(x): return np.sign(x)
def log_abs(x): return np.sign(x) * np.log1p(np.abs(x))
def sqrt_abs(x): return np.sign(x) * np.sqrt(np.abs(x))


def cs_rank(x):
    filled = np.where(np.isnan(x), np.inf, x)
    order = np.argsort(filled, axis=1, kind="stable")
    positions = np.broadcast_to(np.arange(1, x.shape[1] + 1, dtype=np.float64), x.shape)
    ranks = np.empty(x.shape, dtype=np.float64)
    np.put_along_axis(ranks, order, positions, axis=1)
    valid = ~np.isnan(x)
    counts = np.maximum(valid.sum(axis=1, keepdims=True), 1)
    return np.where(valid, ranks / counts, np.nan)


def cs_zscore(x):
    mean, std = _nan_mean_std(x)
    return np.where(std < EPS, np.nan, (x - mean) / np.where(std < EPS, 1.0, std))


def cs_demean(x):
    mean, _ = _nan_mean_std(x)
    return x - mean


OPS = {{
    "add": add, "sub": sub, "mul": mul, "div": div,
    "neg": neg, "abs": abs_, "sign": sign, "log": log_abs, "sqrt": sqrt_abs,
    "cs_rank": cs_rank, "cs_zscore": cs_zscore, "cs_demean": cs_demean,
}}


# ------------------------------------------------------------------ slot packing --
def pack(df, columns):
    """Long frame -> (T, N_max) slot grids. Slot j is a DIFFERENT stock on each date.

    Grids are built at float32 and only then widened to float64, mirroring Helix's own
    packing exactly. This is not cosmetic: cs_rank sorts, and float32 rounding can make
    two float64-distinct values tie, which would reorder ranks relative to the search.
    """
    dates, date_pos = np.unique(df[DATE_COLUMN].to_numpy(), return_inverse=True)
    counts = np.bincount(date_pos, minlength=len(dates))
    n_max = int(counts.max())
    starts = np.concatenate([[0], np.cumsum(counts)[:-1]])
    slot = np.arange(len(df)) - np.repeat(starts, counts)

    occupied = np.zeros((len(dates), n_max), dtype=bool)
    occupied[date_pos, slot] = True

    grids = {{}}
    for column in columns:
        grid = np.full((len(dates), n_max), np.nan, dtype=np.float32)
        grid[date_pos, slot] = pd.to_numeric(df[column], errors="coerce").to_numpy()
        grids[column] = grid.astype(np.float64)
    return dates, date_pos, slot, occupied, grids


# ------------------------------------------------------------------------- metrics --
def daily_ic(factor, target, mask, min_samples=30):
    valid = mask & np.isfinite(factor) & np.isfinite(target)
    x = cs_rank(np.where(valid, factor, np.nan))
    y = cs_rank(np.where(valid, target, np.nan))
    w = valid.astype(np.float64)
    xs, ys = np.nan_to_num(x) * w, np.nan_to_num(y) * w
    n = w.sum(axis=1)
    sx, sy = xs.sum(axis=1), ys.sum(axis=1)
    cov = n * (xs * ys).sum(axis=1) - sx * sy
    vx = n * (xs * xs).sum(axis=1) - sx * sx
    vy = n * (ys * ys).sum(axis=1) - sy * sy
    denom = np.sqrt(np.maximum(vx, 0) * np.maximum(vy, 0))
    with np.errstate(invalid="ignore", divide="ignore"):
        ic = np.where(denom > 0, cov / np.where(denom > 0, denom, 1.0), np.nan)
    return np.where(n >= min_samples, ic, np.nan)


def summarize(ic):
    f = ic[np.isfinite(ic)]
    if f.size == 0:
        return {{}}
    mean = float(f.mean())
    std = float(f.std(ddof=1)) if f.size > 1 else float("nan")
    icir = mean / std if std and std > 0 else float("nan")
    return {{
        "ic_mean": round(mean, 6),
        "ic_std": round(std, 6),
        "icir": round(icir, 4),
        "icir_ann": round(icir * np.sqrt(252), 3),
        "t_stat": round(icir * np.sqrt(f.size), 3),
        "positive_rate": round(float((f > 0).mean()), 4),
        "n_days": int(f.size),
    }}


# ---------------------------------------------------------------------------- main --
def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input", required=True)
    ap.add_argument("--output", default="")
    ap.add_argument("--report", default="factor_ic_report.json")
    ap.add_argument("--min-samples", type=int, default=30)
    ap.add_argument(
        "--ic-since", default=SEARCH_END,
        help="Only score dates strictly after this one. Defaults to the last date the "
             "factors were mined on, so the reported IC is genuinely out-of-sample. "
             "Pass an empty string to score the full history instead.",
    )
    args = ap.parse_args()

    df = pd.read_parquet(args.input)
    missing = [c for c in FIELD_NAMES if c not in df.columns]
    if missing:
        raise SystemExit("input is missing required feature columns: %s" % missing[:10])

    df[DATE_COLUMN] = df[DATE_COLUMN].astype(str)
    df[CODE_COLUMN] = df[CODE_COLUMN].astype(str)
    order = np.lexsort((df[CODE_COLUMN].to_numpy(), df[DATE_COLUMN].to_numpy()))
    df = df.iloc[order].reset_index(drop=True)

    targets = [t for t in IC_TARGETS if t in df.columns]
    dates, date_pos, slot, occupied, grids = pack(df, list(FIELD_NAMES) + targets)
    print("packed %d dates x %d slots (%d rows)" % (len(dates), occupied.shape[1], len(df)))

    # Factor columns are written for every row; IC is only measured after the search
    # window, otherwise the number reported here is partly in-sample.
    scored = occupied & (dates > args.ic_since)[:, None] if args.ic_since else occupied
    print("scoring IC on %d of %d dates (--ic-since %r)" % (
        int((scored.any(axis=1)).sum()), len(dates), args.ic_since))

    namespace = {{**OPS, **{{name: grids[name] for name in FIELD_NAMES}}}}
    report = {{"_meta": {{"ic_since": args.ic_since, "n_dates_scored": int(scored.any(axis=1).sum())}}}}
    for spec in FACTORS:
        with np.errstate(all="ignore"):
            values = eval(spec["expression"], {{"__builtins__": {{}}}}, namespace)  # noqa: S307
        values = np.where(np.isfinite(values), values, np.nan) * spec["sign"]
        df[spec["name"]] = values[date_pos, slot]

        entry = {{"expression": spec["expression"], "sign": spec["sign"]}}
        for target in targets:
            entry[target] = summarize(
                daily_ic(values, grids[target], scored, args.min_samples)
            )
        report[spec["name"]] = entry
        head = entry.get(targets[0], {{}}) if targets else {{}}
        print("  %-12s IC %+.5f  ICIR %+.3f  ann %+.2f  pos %.1f%%  %s" % (
            spec["name"], head.get("ic_mean", float("nan")), head.get("icir", float("nan")),
            head.get("icir_ann", float("nan")), 100 * head.get("positive_rate", float("nan")),
            spec["expression"][:60],
        ))

    with open(args.report, "w") as fh:
        json.dump(report, fh, indent=2, ensure_ascii=False)
    print("wrote %s" % args.report)

    if args.output:
        df.to_parquet(args.output, index=False, compression="zstd")
        print("wrote %s (%d columns, +%d factors)" % (
            args.output, df.shape[1], len(FACTORS)))


if __name__ == "__main__":
    main()
'''


def render_apply_script(
    library: FactorLibrary,
    ic_targets: list[str],
    date_column: str = "trade_date",
    code_column: str = "stock_code",
    search_end: str = "",
) -> str:
    """Build the standalone script source for ``library``."""
    if library.kind != "event":
        raise ValueError(f"apply-script export is for event libraries, got {library.kind!r}")

    invalid = [n for n in library.field_names if not n.isidentifier()]
    if invalid:
        raise ValueError(
            f"these column names are not valid Python identifiers and cannot appear in an "
            f"evaluated expression: {invalid}"
        )

    factors = [
        {"name": f.name, "expression": f.expression, "sign": f.sign} for f in library.factors
    ]
    return _TEMPLATE.format(
        n_factors=len(factors),
        date_column=date_column,
        code_column=code_column,
        search_end=search_end,
        field_names=json.dumps(library.field_names, indent=4),
        factors_json=json.dumps(factors, ensure_ascii=False),
        ic_targets=json.dumps(ic_targets),
    )


def write_apply_script(
    path: Path, library: FactorLibrary, ic_targets: list[str], search_end: str = ""
) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        render_apply_script(library, ic_targets, search_end=search_end), encoding="utf-8"
    )
    path.chmod(0o755)
    log.info("wrote standalone apply script for %d factors to %s", len(library.factors), path)
    return path
